/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DataRoomInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_BATCH_SIZE"
      | "NO_PARENT"
      | "addDocuments"
      | "admin"
      | "createFolder"
      | "createRoom"
      | "documentKeyVersion"
      | "getDocument"
      | "getFolders"
      | "getMembers"
      | "getParentRoom"
      | "getRoom"
      | "getRoomKey"
      | "grantAccess"
      | "grantAccessToAllFolders"
      | "hasAccess"
      | "initialize"
      | "operator"
      | "ownerOf"
      | "rekeyRoom"
      | "removeDocument"
      | "renameRoom"
      | "revokeAccess"
      | "revokeAccessFromAllFolders"
      | "revokeAndRekey"
      | "roomCount"
      | "roomKeyVersion"
      | "rooms"
      | "setAdmin"
      | "updateDocumentKeys"
      | "updateDocumentMetadata"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "DocumentAdded"
      | "DocumentRemoved"
      | "FolderCreated"
      | "MembershipChanged"
      | "RoomCreated"
      | "RoomRekeyed"
      | "RoomRenamed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "NO_PARENT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addDocuments",
    values: [BigNumberish, string[], string[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createFolder",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "createRoom", values: [string]): string;
  encodeFunctionData(
    functionFragment: "documentKeyVersion",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDocument",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFolders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMembers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParentRoom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoomKey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccessToAllFolders",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rekeyRoom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDocument",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renameRoom",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccessFromAllFolders",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAndRekey",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(functionFragment: "roomCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "roomKeyVersion",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "rooms", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDocumentKeys",
    values: [BigNumberish, BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDocumentMetadata",
    values: [BigNumberish, BigNumberish[], BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_BATCH_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "NO_PARENT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addDocuments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createFolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createRoom", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "documentKeyVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFolders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMembers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getParentRoom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRoom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRoomKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccessToAllFolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rekeyRoom", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "renameRoom", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccessFromAllFolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAndRekey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roomCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roomKeyVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rooms", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateDocumentKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDocumentMetadata",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentAddedEvent {
  export type InputTuple = [roomId: BigNumberish, docIndex: BigNumberish];
  export type OutputTuple = [roomId: bigint, docIndex: bigint];
  export interface OutputObject {
    roomId: bigint;
    docIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentRemovedEvent {
  export type InputTuple = [roomId: BigNumberish, docIndex: BigNumberish];
  export type OutputTuple = [roomId: bigint, docIndex: bigint];
  export interface OutputObject {
    roomId: bigint;
    docIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FolderCreatedEvent {
  export type InputTuple = [parentId: BigNumberish, roomId: BigNumberish];
  export type OutputTuple = [parentId: bigint, roomId: bigint];
  export interface OutputObject {
    parentId: bigint;
    roomId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MembershipChangedEvent {
  export type InputTuple = [roomId: BigNumberish];
  export type OutputTuple = [roomId: bigint];
  export interface OutputObject {
    roomId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomCreatedEvent {
  export type InputTuple = [roomId: BigNumberish, creator: AddressLike];
  export type OutputTuple = [roomId: bigint, creator: string];
  export interface OutputObject {
    roomId: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomRekeyedEvent {
  export type InputTuple = [roomId: BigNumberish, newVersion: BigNumberish];
  export type OutputTuple = [roomId: bigint, newVersion: bigint];
  export interface OutputObject {
    roomId: bigint;
    newVersion: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomRenamedEvent {
  export type InputTuple = [roomId: BigNumberish, newName: string];
  export type OutputTuple = [roomId: bigint, newName: string];
  export interface OutputObject {
    roomId: bigint;
    newName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DataRoom extends BaseContract {
  connect(runner?: ContractRunner | null): DataRoom;
  waitForDeployment(): Promise<this>;

  interface: DataRoomInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  NO_PARENT: TypedContractMethod<[], [bigint], "view">;

  addDocuments: TypedContractMethod<
    [
      roomId: BigNumberish,
      cids: string[],
      names: string[],
      wrappedKeys: BytesLike[],
      metadata: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  createFolder: TypedContractMethod<
    [parentId: BigNumberish, name: string],
    [bigint],
    "nonpayable"
  >;

  createRoom: TypedContractMethod<[name: string], [bigint], "nonpayable">;

  documentKeyVersion: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getDocument: TypedContractMethod<
    [roomId: BigNumberish, docIndex: BigNumberish],
    [
      [string, string, bigint, bigint, string, string] & {
        cid: string;
        name: string;
        createdAt: bigint;
        keyVersion: bigint;
        wrappedKey: string;
        metadata: string;
      }
    ],
    "view"
  >;

  getFolders: TypedContractMethod<[parentId: BigNumberish], [bigint[]], "view">;

  getMembers: TypedContractMethod<[roomId: BigNumberish], [string[]], "view">;

  getParentRoom: TypedContractMethod<[roomId: BigNumberish], [bigint], "view">;

  getRoom: TypedContractMethod<
    [roomId: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint, bigint] & {
        name: string;
        documentCount: bigint;
        memberCount: bigint;
        isParent: boolean;
        parentId: bigint;
        childCount: bigint;
      }
    ],
    "view"
  >;

  getRoomKey: TypedContractMethod<[roomId: BigNumberish], [string], "view">;

  grantAccess: TypedContractMethod<
    [roomId: BigNumberish, users: AddressLike[]],
    [void],
    "nonpayable"
  >;

  grantAccessToAllFolders: TypedContractMethod<
    [parentId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;

  hasAccess: TypedContractMethod<[roomId: BigNumberish], [boolean], "view">;

  initialize: TypedContractMethod<
    [_admin: AddressLike, _operator: AddressLike],
    [void],
    "nonpayable"
  >;

  operator: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[roomId: BigNumberish], [string], "view">;

  rekeyRoom: TypedContractMethod<[roomId: BigNumberish], [void], "nonpayable">;

  removeDocument: TypedContractMethod<
    [roomId: BigNumberish, docIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  renameRoom: TypedContractMethod<
    [roomId: BigNumberish, newName: string],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [roomId: BigNumberish, users: AddressLike[]],
    [void],
    "nonpayable"
  >;

  revokeAccessFromAllFolders: TypedContractMethod<
    [parentId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeAndRekey: TypedContractMethod<
    [roomId: BigNumberish, users: AddressLike[]],
    [void],
    "nonpayable"
  >;

  roomCount: TypedContractMethod<[], [bigint], "view">;

  roomKeyVersion: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  rooms: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, bigint, bigint] & {
        owner: string;
        name: string;
        documentCount: bigint;
        memberCount: bigint;
        isParent: boolean;
        parentId: bigint;
        childCount: bigint;
      }
    ],
    "view"
  >;

  setAdmin: TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;

  updateDocumentKeys: TypedContractMethod<
    [
      roomId: BigNumberish,
      docIndices: BigNumberish[],
      newWrappedKeys: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  updateDocumentMetadata: TypedContractMethod<
    [roomId: BigNumberish, docIndices: BigNumberish[], metadata: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NO_PARENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addDocuments"
  ): TypedContractMethod<
    [
      roomId: BigNumberish,
      cids: string[],
      names: string[],
      wrappedKeys: BytesLike[],
      metadata: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createFolder"
  ): TypedContractMethod<
    [parentId: BigNumberish, name: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createRoom"
  ): TypedContractMethod<[name: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "documentKeyVersion"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDocument"
  ): TypedContractMethod<
    [roomId: BigNumberish, docIndex: BigNumberish],
    [
      [string, string, bigint, bigint, string, string] & {
        cid: string;
        name: string;
        createdAt: bigint;
        keyVersion: bigint;
        wrappedKey: string;
        metadata: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFolders"
  ): TypedContractMethod<[parentId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMembers"
  ): TypedContractMethod<[roomId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getParentRoom"
  ): TypedContractMethod<[roomId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoom"
  ): TypedContractMethod<
    [roomId: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint, bigint] & {
        name: string;
        documentCount: bigint;
        memberCount: bigint;
        isParent: boolean;
        parentId: bigint;
        childCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoomKey"
  ): TypedContractMethod<[roomId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [roomId: BigNumberish, users: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantAccessToAllFolders"
  ): TypedContractMethod<
    [parentId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<[roomId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_admin: AddressLike, _operator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[roomId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "rekeyRoom"
  ): TypedContractMethod<[roomId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeDocument"
  ): TypedContractMethod<
    [roomId: BigNumberish, docIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renameRoom"
  ): TypedContractMethod<
    [roomId: BigNumberish, newName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [roomId: BigNumberish, users: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccessFromAllFolders"
  ): TypedContractMethod<
    [parentId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAndRekey"
  ): TypedContractMethod<
    [roomId: BigNumberish, users: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roomCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "roomKeyVersion"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "rooms"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, bigint, bigint] & {
        owner: string;
        name: string;
        documentCount: bigint;
        memberCount: bigint;
        isParent: boolean;
        parentId: bigint;
        childCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateDocumentKeys"
  ): TypedContractMethod<
    [
      roomId: BigNumberish,
      docIndices: BigNumberish[],
      newWrappedKeys: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateDocumentMetadata"
  ): TypedContractMethod<
    [roomId: BigNumberish, docIndices: BigNumberish[], metadata: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "DocumentAdded"
  ): TypedContractEvent<
    DocumentAddedEvent.InputTuple,
    DocumentAddedEvent.OutputTuple,
    DocumentAddedEvent.OutputObject
  >;
  getEvent(
    key: "DocumentRemoved"
  ): TypedContractEvent<
    DocumentRemovedEvent.InputTuple,
    DocumentRemovedEvent.OutputTuple,
    DocumentRemovedEvent.OutputObject
  >;
  getEvent(
    key: "FolderCreated"
  ): TypedContractEvent<
    FolderCreatedEvent.InputTuple,
    FolderCreatedEvent.OutputTuple,
    FolderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MembershipChanged"
  ): TypedContractEvent<
    MembershipChangedEvent.InputTuple,
    MembershipChangedEvent.OutputTuple,
    MembershipChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoomCreated"
  ): TypedContractEvent<
    RoomCreatedEvent.InputTuple,
    RoomCreatedEvent.OutputTuple,
    RoomCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RoomRekeyed"
  ): TypedContractEvent<
    RoomRekeyedEvent.InputTuple,
    RoomRekeyedEvent.OutputTuple,
    RoomRekeyedEvent.OutputObject
  >;
  getEvent(
    key: "RoomRenamed"
  ): TypedContractEvent<
    RoomRenamedEvent.InputTuple,
    RoomRenamedEvent.OutputTuple,
    RoomRenamedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "DocumentAdded(uint256,uint256)": TypedContractEvent<
      DocumentAddedEvent.InputTuple,
      DocumentAddedEvent.OutputTuple,
      DocumentAddedEvent.OutputObject
    >;
    DocumentAdded: TypedContractEvent<
      DocumentAddedEvent.InputTuple,
      DocumentAddedEvent.OutputTuple,
      DocumentAddedEvent.OutputObject
    >;

    "DocumentRemoved(uint256,uint256)": TypedContractEvent<
      DocumentRemovedEvent.InputTuple,
      DocumentRemovedEvent.OutputTuple,
      DocumentRemovedEvent.OutputObject
    >;
    DocumentRemoved: TypedContractEvent<
      DocumentRemovedEvent.InputTuple,
      DocumentRemovedEvent.OutputTuple,
      DocumentRemovedEvent.OutputObject
    >;

    "FolderCreated(uint256,uint256)": TypedContractEvent<
      FolderCreatedEvent.InputTuple,
      FolderCreatedEvent.OutputTuple,
      FolderCreatedEvent.OutputObject
    >;
    FolderCreated: TypedContractEvent<
      FolderCreatedEvent.InputTuple,
      FolderCreatedEvent.OutputTuple,
      FolderCreatedEvent.OutputObject
    >;

    "MembershipChanged(uint256)": TypedContractEvent<
      MembershipChangedEvent.InputTuple,
      MembershipChangedEvent.OutputTuple,
      MembershipChangedEvent.OutputObject
    >;
    MembershipChanged: TypedContractEvent<
      MembershipChangedEvent.InputTuple,
      MembershipChangedEvent.OutputTuple,
      MembershipChangedEvent.OutputObject
    >;

    "RoomCreated(uint256,address)": TypedContractEvent<
      RoomCreatedEvent.InputTuple,
      RoomCreatedEvent.OutputTuple,
      RoomCreatedEvent.OutputObject
    >;
    RoomCreated: TypedContractEvent<
      RoomCreatedEvent.InputTuple,
      RoomCreatedEvent.OutputTuple,
      RoomCreatedEvent.OutputObject
    >;

    "RoomRekeyed(uint256,uint256)": TypedContractEvent<
      RoomRekeyedEvent.InputTuple,
      RoomRekeyedEvent.OutputTuple,
      RoomRekeyedEvent.OutputObject
    >;
    RoomRekeyed: TypedContractEvent<
      RoomRekeyedEvent.InputTuple,
      RoomRekeyedEvent.OutputTuple,
      RoomRekeyedEvent.OutputObject
    >;

    "RoomRenamed(uint256,string)": TypedContractEvent<
      RoomRenamedEvent.InputTuple,
      RoomRenamedEvent.OutputTuple,
      RoomRenamedEvent.OutputObject
    >;
    RoomRenamed: TypedContractEvent<
      RoomRenamedEvent.InputTuple,
      RoomRenamedEvent.OutputTuple,
      RoomRenamedEvent.OutputObject
    >;
  };
}
