/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DataRoom } from "./DataRoom";
export * as factories from "./factories";
export { DataRoom__factory } from "./factories/DataRoom__factory";
