/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SecretsVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PERMANENT"
      | "createNamespace"
      | "deleteSecret"
      | "getNamespace"
      | "getNamespaceAccessExpiry"
      | "getNamespaceGrantees"
      | "getNamespacesByGrantee"
      | "getNamespacesByOwner"
      | "getNsKeyHandle"
      | "getSecret"
      | "getSecretAccessExpiry"
      | "getSecretGrantees"
      | "getSecretKeyHandle"
      | "getSecretKeys"
      | "grantNamespaceAccess"
      | "grantSecretAccess"
      | "hasAccess"
      | "multicall"
      | "namespaceCount"
      | "owner"
      | "renounceOwnership"
      | "revokeNamespaceAccess"
      | "revokeSecretAccess"
      | "rotateNamespaceKey"
      | "rotateSecretKey"
      | "setSecret"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "NamespaceAccessGranted"
      | "NamespaceAccessRevoked"
      | "NamespaceCreated"
      | "NamespaceKeyRotated"
      | "OwnershipTransferred"
      | "SecretAccessGranted"
      | "SecretAccessRevoked"
      | "SecretDeleted"
      | "SecretKeyRotated"
      | "SecretSet"
  ): EventFragment;

  encodeFunctionData(functionFragment: "PERMANENT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createNamespace",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteSecret",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getNamespace",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNamespaceAccessExpiry",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNamespaceGrantees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNamespacesByGrantee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNamespacesByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNsKeyHandle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSecret",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSecretAccessExpiry",
    values: [BigNumberish, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSecretGrantees",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSecretKeyHandle",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSecretKeys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantNamespaceAccess",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantSecretAccess",
    values: [BigNumberish, string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "namespaceCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeNamespaceAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeSecretAccess",
    values: [BigNumberish, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotateNamespaceKey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rotateSecretKey",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSecret",
    values: [BigNumberish, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "PERMANENT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createNamespace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteSecret",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNamespace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNamespaceAccessExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNamespaceGrantees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNamespacesByGrantee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNamespacesByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNsKeyHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSecret", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSecretAccessExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSecretGrantees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSecretKeyHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSecretKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantNamespaceAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantSecretAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "namespaceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeNamespaceAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeSecretAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotateNamespaceKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotateSecretKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSecret", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace NamespaceAccessGrantedEvent {
  export type InputTuple = [
    namespaceId: BigNumberish,
    account: AddressLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    namespaceId: bigint,
    account: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    namespaceId: bigint;
    account: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NamespaceAccessRevokedEvent {
  export type InputTuple = [namespaceId: BigNumberish, account: AddressLike];
  export type OutputTuple = [namespaceId: bigint, account: string];
  export interface OutputObject {
    namespaceId: bigint;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NamespaceCreatedEvent {
  export type InputTuple = [
    namespaceId: BigNumberish,
    owner: AddressLike,
    name: string
  ];
  export type OutputTuple = [namespaceId: bigint, owner: string, name: string];
  export interface OutputObject {
    namespaceId: bigint;
    owner: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NamespaceKeyRotatedEvent {
  export type InputTuple = [namespaceId: BigNumberish];
  export type OutputTuple = [namespaceId: bigint];
  export interface OutputObject {
    namespaceId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecretAccessGrantedEvent {
  export type InputTuple = [
    namespaceId: BigNumberish,
    keyHash: BytesLike,
    account: AddressLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    namespaceId: bigint,
    keyHash: string,
    account: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    namespaceId: bigint;
    keyHash: string;
    account: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecretAccessRevokedEvent {
  export type InputTuple = [
    namespaceId: BigNumberish,
    keyHash: BytesLike,
    account: AddressLike
  ];
  export type OutputTuple = [
    namespaceId: bigint,
    keyHash: string,
    account: string
  ];
  export interface OutputObject {
    namespaceId: bigint;
    keyHash: string;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecretDeletedEvent {
  export type InputTuple = [namespaceId: BigNumberish, keyHash: BytesLike];
  export type OutputTuple = [namespaceId: bigint, keyHash: string];
  export interface OutputObject {
    namespaceId: bigint;
    keyHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecretKeyRotatedEvent {
  export type InputTuple = [namespaceId: BigNumberish, keyHash: BytesLike];
  export type OutputTuple = [namespaceId: bigint, keyHash: string];
  export interface OutputObject {
    namespaceId: bigint;
    keyHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecretSetEvent {
  export type InputTuple = [namespaceId: BigNumberish, keyHash: BytesLike];
  export type OutputTuple = [namespaceId: bigint, keyHash: string];
  export interface OutputObject {
    namespaceId: bigint;
    keyHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecretsVault extends BaseContract {
  connect(runner?: ContractRunner | null): SecretsVault;
  waitForDeployment(): Promise<this>;

  interface: SecretsVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PERMANENT: TypedContractMethod<[], [bigint], "view">;

  createNamespace: TypedContractMethod<[name: string], [bigint], "nonpayable">;

  deleteSecret: TypedContractMethod<
    [namespaceId: BigNumberish, key: string],
    [void],
    "nonpayable"
  >;

  getNamespace: TypedContractMethod<
    [namespaceId: BigNumberish],
    [
      [string, string, bigint] & {
        owner: string;
        name: string;
        secretCount: bigint;
      }
    ],
    "view"
  >;

  getNamespaceAccessExpiry: TypedContractMethod<
    [namespaceId: BigNumberish, account: AddressLike],
    [bigint],
    "view"
  >;

  getNamespaceGrantees: TypedContractMethod<
    [namespaceId: BigNumberish],
    [string[]],
    "view"
  >;

  getNamespacesByGrantee: TypedContractMethod<
    [account: AddressLike],
    [bigint[]],
    "view"
  >;

  getNamespacesByOwner: TypedContractMethod<
    [owner_: AddressLike],
    [bigint[]],
    "view"
  >;

  getNsKeyHandle: TypedContractMethod<
    [namespaceId: BigNumberish],
    [string],
    "view"
  >;

  getSecret: TypedContractMethod<
    [namespaceId: BigNumberish, key: string],
    [
      [string, string, bigint, bigint] & {
        value: string;
        nsValue: string;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  getSecretAccessExpiry: TypedContractMethod<
    [namespaceId: BigNumberish, key: string, account: AddressLike],
    [bigint],
    "view"
  >;

  getSecretGrantees: TypedContractMethod<
    [namespaceId: BigNumberish, key: string],
    [string[]],
    "view"
  >;

  getSecretKeyHandle: TypedContractMethod<
    [namespaceId: BigNumberish, key: string],
    [string],
    "view"
  >;

  getSecretKeys: TypedContractMethod<
    [namespaceId: BigNumberish],
    [string[]],
    "view"
  >;

  grantNamespaceAccess: TypedContractMethod<
    [namespaceId: BigNumberish, account: AddressLike, expiresAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  grantSecretAccess: TypedContractMethod<
    [
      namespaceId: BigNumberish,
      key: string,
      account: AddressLike,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  hasAccess: TypedContractMethod<
    [namespaceId: BigNumberish, keyHash: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  multicall: TypedContractMethod<[data: BytesLike[]], [string[]], "nonpayable">;

  namespaceCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeNamespaceAccess: TypedContractMethod<
    [namespaceId: BigNumberish, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeSecretAccess: TypedContractMethod<
    [namespaceId: BigNumberish, key: string, account: AddressLike],
    [void],
    "nonpayable"
  >;

  rotateNamespaceKey: TypedContractMethod<
    [namespaceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rotateSecretKey: TypedContractMethod<
    [namespaceId: BigNumberish, key: string],
    [void],
    "nonpayable"
  >;

  setSecret: TypedContractMethod<
    [
      namespaceId: BigNumberish,
      key: string,
      value: BytesLike,
      nsValue: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PERMANENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createNamespace"
  ): TypedContractMethod<[name: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteSecret"
  ): TypedContractMethod<
    [namespaceId: BigNumberish, key: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getNamespace"
  ): TypedContractMethod<
    [namespaceId: BigNumberish],
    [
      [string, string, bigint] & {
        owner: string;
        name: string;
        secretCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNamespaceAccessExpiry"
  ): TypedContractMethod<
    [namespaceId: BigNumberish, account: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNamespaceGrantees"
  ): TypedContractMethod<[namespaceId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getNamespacesByGrantee"
  ): TypedContractMethod<[account: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getNamespacesByOwner"
  ): TypedContractMethod<[owner_: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getNsKeyHandle"
  ): TypedContractMethod<[namespaceId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getSecret"
  ): TypedContractMethod<
    [namespaceId: BigNumberish, key: string],
    [
      [string, string, bigint, bigint] & {
        value: string;
        nsValue: string;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSecretAccessExpiry"
  ): TypedContractMethod<
    [namespaceId: BigNumberish, key: string, account: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSecretGrantees"
  ): TypedContractMethod<
    [namespaceId: BigNumberish, key: string],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSecretKeyHandle"
  ): TypedContractMethod<
    [namespaceId: BigNumberish, key: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSecretKeys"
  ): TypedContractMethod<[namespaceId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantNamespaceAccess"
  ): TypedContractMethod<
    [namespaceId: BigNumberish, account: AddressLike, expiresAt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantSecretAccess"
  ): TypedContractMethod<
    [
      namespaceId: BigNumberish,
      key: string,
      account: AddressLike,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [namespaceId: BigNumberish, keyHash: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "multicall"
  ): TypedContractMethod<[data: BytesLike[]], [string[]], "nonpayable">;
  getFunction(
    nameOrSignature: "namespaceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeNamespaceAccess"
  ): TypedContractMethod<
    [namespaceId: BigNumberish, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeSecretAccess"
  ): TypedContractMethod<
    [namespaceId: BigNumberish, key: string, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotateNamespaceKey"
  ): TypedContractMethod<[namespaceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rotateSecretKey"
  ): TypedContractMethod<
    [namespaceId: BigNumberish, key: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSecret"
  ): TypedContractMethod<
    [
      namespaceId: BigNumberish,
      key: string,
      value: BytesLike,
      nsValue: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "NamespaceAccessGranted"
  ): TypedContractEvent<
    NamespaceAccessGrantedEvent.InputTuple,
    NamespaceAccessGrantedEvent.OutputTuple,
    NamespaceAccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "NamespaceAccessRevoked"
  ): TypedContractEvent<
    NamespaceAccessRevokedEvent.InputTuple,
    NamespaceAccessRevokedEvent.OutputTuple,
    NamespaceAccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "NamespaceCreated"
  ): TypedContractEvent<
    NamespaceCreatedEvent.InputTuple,
    NamespaceCreatedEvent.OutputTuple,
    NamespaceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "NamespaceKeyRotated"
  ): TypedContractEvent<
    NamespaceKeyRotatedEvent.InputTuple,
    NamespaceKeyRotatedEvent.OutputTuple,
    NamespaceKeyRotatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SecretAccessGranted"
  ): TypedContractEvent<
    SecretAccessGrantedEvent.InputTuple,
    SecretAccessGrantedEvent.OutputTuple,
    SecretAccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "SecretAccessRevoked"
  ): TypedContractEvent<
    SecretAccessRevokedEvent.InputTuple,
    SecretAccessRevokedEvent.OutputTuple,
    SecretAccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SecretDeleted"
  ): TypedContractEvent<
    SecretDeletedEvent.InputTuple,
    SecretDeletedEvent.OutputTuple,
    SecretDeletedEvent.OutputObject
  >;
  getEvent(
    key: "SecretKeyRotated"
  ): TypedContractEvent<
    SecretKeyRotatedEvent.InputTuple,
    SecretKeyRotatedEvent.OutputTuple,
    SecretKeyRotatedEvent.OutputObject
  >;
  getEvent(
    key: "SecretSet"
  ): TypedContractEvent<
    SecretSetEvent.InputTuple,
    SecretSetEvent.OutputTuple,
    SecretSetEvent.OutputObject
  >;

  filters: {
    "NamespaceAccessGranted(uint256,address,uint256)": TypedContractEvent<
      NamespaceAccessGrantedEvent.InputTuple,
      NamespaceAccessGrantedEvent.OutputTuple,
      NamespaceAccessGrantedEvent.OutputObject
    >;
    NamespaceAccessGranted: TypedContractEvent<
      NamespaceAccessGrantedEvent.InputTuple,
      NamespaceAccessGrantedEvent.OutputTuple,
      NamespaceAccessGrantedEvent.OutputObject
    >;

    "NamespaceAccessRevoked(uint256,address)": TypedContractEvent<
      NamespaceAccessRevokedEvent.InputTuple,
      NamespaceAccessRevokedEvent.OutputTuple,
      NamespaceAccessRevokedEvent.OutputObject
    >;
    NamespaceAccessRevoked: TypedContractEvent<
      NamespaceAccessRevokedEvent.InputTuple,
      NamespaceAccessRevokedEvent.OutputTuple,
      NamespaceAccessRevokedEvent.OutputObject
    >;

    "NamespaceCreated(uint256,address,string)": TypedContractEvent<
      NamespaceCreatedEvent.InputTuple,
      NamespaceCreatedEvent.OutputTuple,
      NamespaceCreatedEvent.OutputObject
    >;
    NamespaceCreated: TypedContractEvent<
      NamespaceCreatedEvent.InputTuple,
      NamespaceCreatedEvent.OutputTuple,
      NamespaceCreatedEvent.OutputObject
    >;

    "NamespaceKeyRotated(uint256)": TypedContractEvent<
      NamespaceKeyRotatedEvent.InputTuple,
      NamespaceKeyRotatedEvent.OutputTuple,
      NamespaceKeyRotatedEvent.OutputObject
    >;
    NamespaceKeyRotated: TypedContractEvent<
      NamespaceKeyRotatedEvent.InputTuple,
      NamespaceKeyRotatedEvent.OutputTuple,
      NamespaceKeyRotatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SecretAccessGranted(uint256,bytes32,address,uint256)": TypedContractEvent<
      SecretAccessGrantedEvent.InputTuple,
      SecretAccessGrantedEvent.OutputTuple,
      SecretAccessGrantedEvent.OutputObject
    >;
    SecretAccessGranted: TypedContractEvent<
      SecretAccessGrantedEvent.InputTuple,
      SecretAccessGrantedEvent.OutputTuple,
      SecretAccessGrantedEvent.OutputObject
    >;

    "SecretAccessRevoked(uint256,bytes32,address)": TypedContractEvent<
      SecretAccessRevokedEvent.InputTuple,
      SecretAccessRevokedEvent.OutputTuple,
      SecretAccessRevokedEvent.OutputObject
    >;
    SecretAccessRevoked: TypedContractEvent<
      SecretAccessRevokedEvent.InputTuple,
      SecretAccessRevokedEvent.OutputTuple,
      SecretAccessRevokedEvent.OutputObject
    >;

    "SecretDeleted(uint256,bytes32)": TypedContractEvent<
      SecretDeletedEvent.InputTuple,
      SecretDeletedEvent.OutputTuple,
      SecretDeletedEvent.OutputObject
    >;
    SecretDeleted: TypedContractEvent<
      SecretDeletedEvent.InputTuple,
      SecretDeletedEvent.OutputTuple,
      SecretDeletedEvent.OutputObject
    >;

    "SecretKeyRotated(uint256,bytes32)": TypedContractEvent<
      SecretKeyRotatedEvent.InputTuple,
      SecretKeyRotatedEvent.OutputTuple,
      SecretKeyRotatedEvent.OutputObject
    >;
    SecretKeyRotated: TypedContractEvent<
      SecretKeyRotatedEvent.InputTuple,
      SecretKeyRotatedEvent.OutputTuple,
      SecretKeyRotatedEvent.OutputObject
    >;

    "SecretSet(uint256,bytes32)": TypedContractEvent<
      SecretSetEvent.InputTuple,
      SecretSetEvent.OutputTuple,
      SecretSetEvent.OutputObject
    >;
    SecretSet: TypedContractEvent<
      SecretSetEvent.InputTuple,
      SecretSetEvent.OutputTuple,
      SecretSetEvent.OutputObject
    >;
  };
}
